/* ── FlowForge i18n ── */
const FF_LANG = {
  en: {
    /* NAV */
    'nav.services': 'Services',
    'nav.work': 'Work',
    'nav.pricing': 'Pricing',
    'nav.cta': 'Get a Quote',

    /* HERO (index) */
    'hero.badge': 'Utah-based · Globally delivered',
    'hero.urgency': 'Currently accepting <strong>3 new projects</strong> — slots filling fast',
    'hero.h1': 'We <span class="gradient-text">forge</span> AI tools,<br>automations &amp;<br>digital experiences.',
    'hero.sub': 'FlowForge builds the software infrastructure modern businesses need — custom AI integrations, browser extensions, automation workflows, and web design that actually converts.',
    'hero.cta1': 'Start a Project',
    'hero.cta2': 'See Our Work →',

    /* STATS */
    'stats.shipped': 'Projects Shipped',
    'stats.services': 'Core Services',
    'stats.response': 'Response Time',
    'stats.ownership': 'Ownership Handover',

    /* SERVICES SECTION */
    'services.label': 'What we build',
    'services.h2': 'Services',
    'services.sub': 'End-to-end digital solutions — from idea to deployment.',
    'svc.ai.title': 'AI Integration',
    'svc.ai.desc': 'Connect Claude, GPT, and other AI models to your existing tools. Chatbots, smart search, document analysis, and custom AI workflows.',
    'svc.ai.price': 'From $800',
    'svc.ai.cta': 'Get started →',
    'svc.auto.title': 'Automation Workflows',
    'svc.auto.desc': "Eliminate repetitive tasks with custom automation pipelines. We connect your apps and let the machines do the work so your team doesn't have to.",
    'svc.auto.price': 'From $400',
    'svc.auto.cta': 'Get started →',
    'svc.chrome.title': 'Chrome Extensions',
    'svc.chrome.desc': "Custom browser extensions for internal teams or public markets. Productivity tools, AI overlays, data tools — built to Chrome's latest standards.",
    'svc.chrome.price': 'From $600',
    'svc.chrome.cta': 'Get started →',
    'svc.web.title': 'Web Design & Dev',
    'svc.web.desc': 'Fast, modern websites that look great and convert. Landing pages to full business sites — built clean, mobile-first, and shipped fast.',
    'svc.web.price': 'From $500',
    'svc.web.cta': 'Get started →',
    'svc.social.title': 'Social Media Automation',
    'svc.social.desc': 'Auto-posting, scheduling, cross-platform pipelines and DM automation. We wire up your social presence so it runs itself while you focus on the business.',
    'svc.social.price': 'From $350',
    'svc.social.cta': 'Get started →',
    'svc.chatbot.title': 'AI Chatbots & Assistants',
    'svc.chatbot.desc': 'Custom AI assistants for WhatsApp, Instagram, websites, and internal tools. Answer questions, qualify leads, and support customers 24/7 automatically.',
    'svc.chatbot.price': 'From $600',
    'svc.chatbot.cta': 'Get started →',

    /* PROCESS */
    'process.label': 'How we work',
    'process.h2': 'Simple process, real results',
    'step1.title': 'Discovery',
    'step1.desc': "We learn your business, your problem, and your goals. One free call — no jargon, just a clear picture of what you need and what it'll cost.",
    'step2.title': 'Build',
    'step2.desc': 'We design, develop, and test. You get progress updates and can give feedback at every step. No surprises, no scope creep.',
    'step3.title': 'Launch',
    'step3.desc': 'We ship, hand over full ownership, and support you post-launch. Your success is the only metric we care about.',

    /* PORTFOLIO */
    'portfolio.label': 'Our work',
    'portfolio.h2': 'Recent Projects',
    'portfolio.sub': 'Real products, shipped and working.',
    'proj.studysnap.title': 'StudySnap',
    'proj.studysnap.desc': 'AI-powered Chrome extension that captures any on-screen question and delivers instant answers with explanations and a confidence score — powered by Claude Vision API.',
    'proj.clarity.title': 'Clarity Extension',
    'proj.clarity.desc': 'Browser extension that detects and highlights dark patterns on websites in real time — protecting users from manipulative UX tricks while browsing.',
    'proj.foto.title': 'FotoExpress Peru',
    'proj.foto.desc': 'Full business website for a photography services company in Peru — modern design, service showcase, and contact flow built for local and international clients.',
    'proj.yours.title': 'Could be yours',
    'proj.yours.desc': "We're actively taking new projects. Your solution could be featured here next. Let's build something that makes a difference.",
    'proj.yours.cta': 'Start a conversation →',

    /* PRICING */
    'pricing.label': 'Investment',
    'pricing.h2': 'Transparent Pricing',
    'pricing.sub': 'Every project is scoped and quoted individually. These are starting points — complex work is quoted after a free discovery call.',
    'price.web.title': 'Web Design',
    'price.web.li1': 'Landing page',
    'price.web.li2': 'Mobile responsive',
    'price.web.li3': 'SEO ready',
    'price.web.li4': 'Full business site from $1,200',
    'price.web.btn': 'Get a quote',
    'price.auto.title': 'Automation',
    'price.auto.li1': 'App-to-app automation',
    'price.auto.li2': 'Trigger + action flows',
    'price.auto.li3': 'Testing & documentation',
    'price.auto.li4': 'Complex n8n from $1,200',
    'price.auto.btn': 'Get a quote',
    'price.ai.title': 'AI Integration',
    'price.ai.li1': 'AI API connection',
    'price.ai.li2': 'Custom prompting & logic',
    'price.ai.li3': 'Testing & deployment',
    'price.ai.li4': 'Full AI systems from $2,500',
    'price.ai.btn': 'Get a quote',
    'price.chrome.title': 'Chrome Extension',
    'price.chrome.li1': 'Manifest V3 compliant',
    'price.chrome.li2': 'Popup + content scripts',
    'price.chrome.li3': 'API integration ready',
    'price.chrome.li4': 'AI-powered from $1,500',
    'price.chrome.btn': 'Get a quote',
    'price.social.title': 'Social Automation',
    'price.social.li1': 'Auto-posting pipelines',
    'price.social.li2': 'DM automation',
    'price.social.li3': 'Cross-platform scheduling',
    'price.social.li4': 'Analytics dashboards from $800',
    'price.social.btn': 'Get a quote',
    'price.chatbot.title': 'AI Chatbot',
    'price.chatbot.li1': 'WhatsApp / Instagram / Web',
    'price.chatbot.li2': 'Custom knowledge base',
    'price.chatbot.li3': 'Lead qualification logic',
    'price.chatbot.li4': 'Multi-platform from $1,500',
    'price.chatbot.btn': 'Get a quote',

    /* FAQ (index) */
    'faq.label': 'Common questions',
    'faq.h2': 'Before you reach out',
    'faq.sub': 'The questions every client asks — answered upfront.',
    'faq.q1': 'How long does a project take?',
    'faq.a1': 'Depends on scope. A landing page takes 3–5 days. A Chrome extension 1–2 weeks. An AI integration 1–3 weeks. We give you a clear timeline before we start — no surprises.',
    'faq.q2': 'Do you require a deposit?',
    'faq.a2': 'Yes — 50% upfront to start, 50% on delivery. This protects both sides and keeps the project moving. We accept bank transfer, PayPal, and Stripe.',
    'faq.q3': "What if I'm not happy with the result?",
    'faq.a3': "We include revision rounds in every project and work with you until it's right. We don't close a project until you're satisfied — that's our standard, not a policy.",
    'faq.q4': 'Can you work with a small budget?',
    'faq.a4': "Yes. Our starting prices reflect real, lean work — no bloated agency overhead. If your budget is tight, tell us and we'll scope something that fits. We'd rather start small than not work together at all.",
    'faq.q5': 'Do I own everything after delivery?',
    'faq.a5': '100%. All code, assets, and accounts are handed over to you at the end of every project. No lock-in, no monthly fees unless you want ongoing support.',
    'faq.q6': 'Do you work with clients outside the US?',
    'faq.a6': "Absolutely — most of our clients are international. We work across time zones, communicate in English and Spanish, and handle remote projects end to end.",

    /* CONTACT (index) */
    'contact.label': "Let's talk",
    'contact.h2': 'Start a project<br>with us',
    'contact.p': "Tell us what you're building or what problem you need solved. We'll respond within 24 hours with a clear path forward — no commitment required.",
    'contact.loc': 'Utah, USA',
    'contact.world': 'Available worldwide',
    'contact.time': 'Response within 24 hours',
    'contact.call': 'Free discovery call included',
    'contact.name.label': 'Name',
    'contact.name.ph': 'Your name',
    'contact.email.label': 'Email',
    'contact.svc.label': 'Service',
    'contact.svc.ph': 'Select a service',
    'contact.budget.label': 'Estimated budget',
    'contact.budget.ph': 'Select a range',
    'contact.msg.label': 'Tell us about your project',
    'contact.msg.ph': 'What are you trying to build or automate?',
    'contact.btn': 'Send Message →',
    'contact.success': "✓ Message sent! We'll be in touch within 24 hours.",

    /* FOOTER */
    'footer.copy': '© 2025 FlowForge · Utah, USA · Globally delivered.',

    /* ── SLC PAGE ── */
    'slc.trust1': 'Utah-based team',
    'slc.trust2': '10+ sites shipped',
    'slc.trust3': 'English & Spanish',
    'slc.trust4': 'Reply in < 24h',
    'slc.trust5': 'You own everything',

    'slc.niches.label': 'Who we work with',
    'slc.niches.h2': 'Built for the businesses<br>that keep Salt Lake City running.',
    'slc.niches.sub': "We're not for everyone. We work with service businesses that are serious about growth — and done with websites that do nothing.",
    'slc.n1.title': 'Home Service Contractors',
    'slc.n1.sub': 'Roofers · HVAC · Plumbers · Landscapers · Electricians',
    'slc.n1.p1': "Your customers Google you before they call. If your website is slow, ugly, or nowhere to be found — they're calling your competitor instead.",
    'slc.n1.p2': 'We build contractor sites that show up on Google, load fast on any phone, and make it dead simple for someone to request a quote in under 30 seconds.',
    'slc.n1.result': '<span>What you get:</span> More quote requests. Fewer no-shows. A site that works while you\'re on the job.',
    'slc.n1.cta': 'Get a free audit →',
    'slc.n2.title': 'Fitness & Wellness Businesses',
    'slc.n2.sub': 'Gyms · Personal trainers · Yoga studios · Massage therapists',
    'slc.n2.p1': 'Your transformation photos are on Instagram. Your booking link is buried in a bio. Your website looks like it was built in 2014.',
    'slc.n2.p2': 'We fix that. We build fitness sites with clear trial offers, class schedules, and booking flows that convert first-time visitors into paying members — without spending more on ads.',
    'slc.n2.result': '<span>What you get:</span> More trial signups. More booked sessions. A site that sells your services around the clock.',
    'slc.n2.cta': 'Get a free audit →',
    'slc.n3.title': 'Latino-Owned Businesses in Utah',
    'slc.n3.sub': 'Restaurants · Salons · Cleaning services · Retail · Any local service',
    'slc.n3.p1': "Your community is here. Your customers speak Spanish and English. Most web agencies don't — and it shows.",
    'slc.n3.p2': 'We build bilingual websites (English + Spanish) that represent your business the right way, connect with your community, and bring in customers from both audiences.',
    'slc.n3.result': '<span>What you get:</span> A site that speaks your language — literally. More customers, more trust, more calls.',
    'slc.n3.cta': "Hablemos / Let's talk →",

    'slc.del.label': 'Deliverables',
    'slc.del.h2': "No mystery. Here's exactly what you get.",
    'slc.del.sub': "Most agencies keep it vague so they can upsell you later. We don't do that.",
    'slc.web.block.title': '🌐 Your Website',
    'slc.web.block.desc': 'A fast, mobile-first site built to convert visitors into customers — not just look pretty.',
    'slc.web.li1': 'Mobile-first design — looks great on any phone',
    'slc.web.li2': '5–8 pages: Home, Services, About, Contact + niche-specific pages',
    'slc.web.li3': 'Fast load times (under 3 seconds — Google cares, so we do too)',
    'slc.web.li4': 'Contact forms and quote request flows built to convert',
    'slc.web.li5': 'Google Maps integration + location pages for local SEO',
    'slc.web.li6': 'Before/after galleries (contractors), booking flows (gyms), bilingual pages (Latino businesses)',
    'slc.web.li7': 'Connected to your Google Business Profile',
    'slc.web.always.title': 'Included in every project',
    'slc.web.always.li1': 'Full ownership — code, domain, accounts',
    'slc.web.always.li2': '30 days of post-launch support',
    'slc.web.always.li3': 'You can update it yourself (or we handle it)',
    'slc.auto.tag': 'Optional Add-on',
    'slc.auto.block.title': '⚡ Automations',
    'slc.auto.block.desc': 'Let the machines handle the follow-up so you can focus on the work. Simple, reliable, wired directly to your phone.',
    'slc.auto.li1': 'Lead capture → instant email or SMS to your prospect',
    'slc.auto.li2': 'New inquiry notifications straight to your phone',
    'slc.auto.li3': 'Weekly summary: how many leads came in, where they came from',
    'slc.auto.li4': 'WhatsApp integration (especially valuable for Latino-owned businesses)',
    'slc.auto.li5': 'Booking confirmation + reminder messages',
    'slc.auto.li6': 'Google review request sent automatically after each job',
    'slc.auto.works.title': 'Works with',
    'slc.auto.works.li1': 'Your existing email and phone',
    'slc.auto.works.li2': 'WhatsApp, Gmail, or any inbox you use',
    'slc.auto.works.li3': 'No new software to learn',

    'slc.proc.label': 'The process',
    'slc.proc.h2': 'Simple process. Real results.',
    'slc.step1.title': 'Free Audit Call',
    'slc.step1.desc': "We look at your current site (or the absence of one), your competitors, and your goals. You get a clear picture of what's broken and what it'll cost to fix it. No commitment, no sales pressure.",
    'slc.step2.title': 'We Build',
    'slc.step2.desc': "You approve the plan. We design, build, and test your site in 2–3 weeks. You get progress updates along the way and can give feedback at every step. No surprises, no scope creep.",
    'slc.step3.title': 'You Get Customers',
    'slc.step3.desc': "Your site goes live. Leads start coming in. We stick around for 30 days to make sure everything is working — then hand over full ownership. The site is yours, forever.",
    'slc.proc.cta': 'Start with a free audit →',

    'slc.cases.label': 'Our work',
    'slc.cases.h2': 'Real businesses. Real results.',
    'slc.cases.sub': 'Products shipped and working — built right here in Utah.',
    'slc.case1.type': 'Contractor · South Salt Lake',
    'slc.case1.title': 'Roofing Co. — SLC',
    'slc.case1.result': '📈 Results incoming',
    'slc.case2.type': 'Fitness Studio · Murray',
    'slc.case2.title': 'Gym / Trainer — SLC',
    'slc.case2.result': '📈 Results incoming',
    'slc.case3.type': 'Latino-owned · West Valley City',
    'slc.case3.title': 'Local Business — SLC',
    'slc.case3.result': '📈 Results incoming',
    'slc.cases.next': 'Want to be our next case study?',
    'slc.cases.cta': "Let's build something together →",

    'slc.pricing.label': 'Offers built for your business',
    'slc.pricing.h2': 'One package per niche.<br>Built around your actual problem.',
    'slc.pricing.sub': "We don't sell one-size-fits-all plans. Here's what we recommend for each type of business — and why.",
    'slc.fp1.name': 'Contractor Growth',
    'slc.fp1.promise': '"A website that gets you found on Google + automated follow-up so no lead goes cold."',
    'slc.fp1.for.label': 'Best for',
    'slc.fp1.for.text': "Contractors already getting some jobs but losing leads because nobody follows up fast enough — or they have no clue how many leads they're even getting.",
    'slc.fp1.li1': 'Mobile-first site — quote request in under 60 seconds',
    'slc.fp1.li2': 'New lead → SMS to you within 60 seconds',
    'slc.fp1.li3': 'Auto-reply to prospect: "We\'ll call you within the hour"',
    'slc.fp1.li4': '3-step follow-up if no response (day 1, 3, 7)',
    'slc.fp1.li5': 'Google review request after every job — automatic',
    'slc.fp1.li6': 'Weekly report: leads in, sources, follow-up status',
    'slc.fp1.li7': '1 site update/month included',
    'slc.fp1.cta': 'Get a Contractor quote',
    'slc.fp1.micro': 'Free audit included. No commitment.',
    'slc.fp2.badge': '⭐ Recommended first step',
    'slc.fp2.name': 'Fitness Launch',
    'slc.fp2.promise': '"A website with a built-in booking flow that converts visitors into trial signups."',
    'slc.fp2.for.label': 'Best for',
    'slc.fp2.for.text': "Trainers and gym owners running on Instagram and word-of-mouth with no real website — or one that has no way to actually book someone.",
    'slc.fp2.li1': '6-page mobile-first site',
    'slc.fp2.li2': 'Trial offer / free consult CTA on every page',
    'slc.fp2.li3': 'Booking form or Calendly integration',
    'slc.fp2.li4': 'Class schedule section built in',
    'slc.fp2.li5': 'Transformation photo gallery',
    'slc.fp2.li6': 'Email capture for free offer (free week, free consult)',
    'slc.fp2.li7': 'Testimonials + social proof section',
    'slc.fp2.li8': 'Full ownership — yours forever',
    'slc.fp2.cta': 'Get a Fitness quote',
    'slc.fp2.micro': 'Free audit included. No commitment.',
    'slc.fp3.name': 'Latino Launch',
    'slc.fp3.promise': '"A bilingual website — English + Spanish — that represents your business the right way and brings in customers from both communities."',
    'slc.fp3.for.label': 'Best for',
    'slc.fp3.for.text': "Latino-owned businesses with no site, an English-only site, or a site that doesn't represent the quality of their business to their community.",
    'slc.fp3.li1': 'Full bilingual site — English + Spanish, every page',
    'slc.fp3.li2': 'Language toggle built in (EN / ES)',
    'slc.fp3.li3': '5–7 pages depending on business type',
    'slc.fp3.li4': 'WhatsApp contact button (floating + in footer)',
    'slc.fp3.li5': 'Photo gallery: food, services, team, space',
    'slc.fp3.li6': 'Google Business Profile bilingual setup',
    'slc.fp3.li7': 'Basic local SEO in both languages',
    'slc.fp3.li8': 'Full ownership — yours forever',
    'slc.fp3.cta': 'Hablemos / Get a quote',
    'slc.fp3.micro': 'Auditoría gratis · Free audit included.',
    'slc.upsell': 'Every Launch package can grow into a <strong>Growth</strong> or <strong>Dominate</strong> monthly plan once your site is live — when you\'re ready for automations, SEO, and a full lead pipeline.',
    'slc.upsell.cta': 'Ask about full package options →',

    'slc.why.label': 'Why us',
    'slc.why.h2': "We're not an agency.<br>We're your local builder.",
    'slc.why1.title': 'Utah-based, SLC-focused',
    'slc.why1.desc': "We're not a remote agency farming your project to a contractor overseas. We're here. We know Salt Lake City, we know the market, and we care about your business because we're building ours here too.",
    'slc.why2.title': 'Bilingual by default',
    'slc.why2.desc': "English and Spanish — not as a gimmick, but as a real capability. If your customers speak Spanish, your website should too. We write it, design it, and make sure it ranks for both audiences.",
    'slc.why3.title': 'Anti-agency, pro-results',
    'slc.why3.desc': "No account managers. No retainer fees for things you don't need. No jargon. You talk directly to the person building your site. We say what we'll do and we do it — on time, every time.",
    'slc.why4.title': 'You own everything',
    'slc.why4.desc': "When we hand over your site, it's yours — code, domain, accounts, all of it. No monthly lock-in, no hidden fees unless you want ongoing support. You're never dependent on us to keep your site alive.",

    'slc.ap.badge': 'New · FlowForge AutoPilot',
    'slc.ap.h2': 'Your marketing on autopilot.<br>Less than $6 a day.',
    'slc.ap.p': 'Once your site is live, add AutoPilot and your marketing runs itself — social posts, lead follow-ups, Google updates, review requests, and a Monday morning report. All done for you, every week, in English and Spanish.',
    'slc.ap.li1': '5 social posts/week — Instagram + Facebook, bilingual',
    'slc.ap.li2': 'New lead → SMS to you in 60 seconds + auto-reply to prospect',
    'slc.ap.li3': 'Google Business Profile updated weekly',
    'slc.ap.li4': 'Review requests sent automatically after every job',
    'slc.ap.li5': 'Weekly report every Monday morning',
    'slc.ap.li6': 'Website chat agent — captures leads 24/7',
    'slc.ap.vs': 'vs $249–399/mo for generic AI tools with no Spanish and no local knowledge',
    'slc.ap.cta': 'Ask about AutoPilot →',
    'slc.ap.note': 'Add-on for FlowForge website clients only.',

    'slc.faq.label': 'Common questions',
    'slc.faq.h2': 'Before you reach out.',
    'slc.faq.sub': 'The questions every SLC business owner asks — answered straight.',
    'slc.faq.q1': "Can't I just use an AI marketing tool instead?",
    'slc.faq.a1': "You can — and some of them are decent at scheduling social posts and writing generic captions. But here's what they can't do: build you a website that actually converts visitors into calls. Fix a Google Business Profile sending people to the wrong address. Write content in real Spanish that sounds like a human, not a translator. Or pick up the phone when something breaks.<br><br>AI tools sit on top of whatever you already have. If what you already have is broken or missing — they just automate the problem. We fix the foundation first. Then we automate on top of something that works.",
    'slc.faq.q2': 'How long does a project take?',
    'slc.faq.a2': "A Launch website is typically done in 2–3 weeks from the day you approve the plan. We move fast because we keep the process simple — one point of contact, no committees, no waiting. You'll see progress every few days, not once a month.",
    'slc.faq.q3': 'Do I have to pay everything upfront?',
    'slc.faq.a3': "No. It's 50% to start, 50% when we deliver. That protects both sides and keeps things moving. We accept bank transfer, PayPal, and Stripe. Monthly plans start after the site is live.",
    'slc.faq.q4': 'What if I already have a website?',
    'slc.faq.a4': "We'll look at it on the free audit call and tell you honestly: fix what you have, or start fresh. Sometimes a few targeted changes are enough. If your current site is too slow, too old, or built on a platform that limits you, we'll tell you that too — and explain why.",
    'slc.faq.q5': 'Do you actually write in Spanish, or just translate?',
    'slc.faq.a5': "We write it. There's a real difference between translated corporate Spanish and copy that sounds natural to a Spanish-speaking community in Utah. We're bilingual — we know the difference, and your customers will too.",
    'slc.faq.q6': 'What do I own at the end?',
    'slc.faq.a6': 'Everything. Code, domain, hosting account, Google Business Profile access — all handed over to you on delivery. No lock-in, no monthly platform fee, no "you can only edit it through us." It\'s yours. Full stop.',

    'slc.final.label': "Let's talk",
    'slc.final.h2': 'Ready to get a website<br>that actually works?',
    'slc.final.p': "Let's start with a free 20-minute audit. We'll look at your current site (or starting point), tell you exactly what's holding you back, and give you a clear plan — no strings attached.<br><br>Most clients walk away with at least 3 things they can fix immediately, whether they work with us or not.",
    'slc.final.btn1': 'Book My Free Audit',
    'slc.final.btn2': 'Message on WhatsApp →',
    'slc.final.micro': 'No commitment. No sales pitch. Just a straight look at your online presence.',
    'slc.final.cities': '📍 Serving Salt Lake City and surrounding areas<br>West Valley City · Murray · Sandy · Draper · South Salt Lake · Millcreek · Provo · Ogden',
  },

  es: {
    /* NAV */
    'nav.services': 'Servicios',
    'nav.work': 'Trabajo',
    'nav.pricing': 'Precios',
    'nav.cta': 'Solicitar Cotización',

    /* HERO (index) */
    'hero.badge': 'Con base en Utah · Entrega global',
    'hero.urgency': 'Aceptando <strong>3 nuevos proyectos</strong> — cupos llenándose rápido',
    'hero.h1': 'Creamos <span class="gradient-text">herramientas</span> de IA,<br>automatizaciones y<br>experiencias digitales.',
    'hero.sub': 'FlowForge construye la infraestructura de software que los negocios modernos necesitan — integraciones de IA, extensiones de navegador, flujos de automatización y diseño web que realmente convierte.',
    'hero.cta1': 'Iniciar un Proyecto',
    'hero.cta2': 'Ver Nuestro Trabajo →',

    /* STATS */
    'stats.shipped': 'Proyectos Entregados',
    'stats.services': 'Servicios Principales',
    'stats.response': 'Tiempo de Respuesta',
    'stats.ownership': 'Traspaso Total',

    /* SERVICES SECTION */
    'services.label': 'Qué construimos',
    'services.h2': 'Servicios',
    'services.sub': 'Soluciones digitales completas — desde la idea hasta el lanzamiento.',
    'svc.ai.title': 'Integración de IA',
    'svc.ai.desc': 'Conecta Claude, GPT y otros modelos de IA a tus herramientas existentes. Chatbots, búsqueda inteligente, análisis de documentos y flujos de trabajo de IA personalizados.',
    'svc.ai.price': 'Desde $800',
    'svc.ai.cta': 'Empezar →',
    'svc.auto.title': 'Flujos de Automatización',
    'svc.auto.desc': 'Elimina las tareas repetitivas con pipelines de automatización personalizados. Conectamos tus apps y dejamos que las máquinas hagan el trabajo.',
    'svc.auto.price': 'Desde $400',
    'svc.auto.cta': 'Empezar →',
    'svc.chrome.title': 'Extensiones de Chrome',
    'svc.chrome.desc': 'Extensiones de navegador personalizadas para equipos internos o mercados públicos. Herramientas de productividad, overlays de IA — con los últimos estándares de Chrome.',
    'svc.chrome.price': 'Desde $600',
    'svc.chrome.cta': 'Empezar →',
    'svc.web.title': 'Diseño y Desarrollo Web',
    'svc.web.desc': 'Sitios web rápidos y modernos que se ven bien y convierten. Desde landing pages hasta sitios completos — mobile-first y entregados rápido.',
    'svc.web.price': 'Desde $500',
    'svc.web.cta': 'Empezar →',
    'svc.social.title': 'Automatización de Redes Sociales',
    'svc.social.desc': 'Auto-publicación, programación, pipelines entre plataformas y automatización de DMs. Tu presencia social funciona sola mientras te enfocas en el negocio.',
    'svc.social.price': 'Desde $350',
    'svc.social.cta': 'Empezar →',
    'svc.chatbot.title': 'Chatbots y Asistentes de IA',
    'svc.chatbot.desc': 'Asistentes de IA personalizados para WhatsApp, Instagram, sitios web y herramientas internas. Responde, califica leads y atiende clientes 24/7 automáticamente.',
    'svc.chatbot.price': 'Desde $600',
    'svc.chatbot.cta': 'Empezar →',

    /* PROCESS */
    'process.label': 'Cómo trabajamos',
    'process.h2': 'Proceso simple, resultados reales',
    'step1.title': 'Descubrimiento',
    'step1.desc': 'Conocemos tu negocio, tu problema y tus objetivos. Una llamada gratuita — sin tecnicismos, solo un panorama claro de lo que necesitas y lo que costará.',
    'step2.title': 'Construcción',
    'step2.desc': 'Diseñamos, desarrollamos y probamos. Recibes actualizaciones y puedes dar retroalimentación en cada paso. Sin sorpresas, sin cambios de alcance.',
    'step3.title': 'Lanzamiento',
    'step3.desc': 'Lanzamos, entregamos la propiedad completa y te apoyamos después del lanzamiento. Tu éxito es la única métrica que nos importa.',

    /* PORTFOLIO */
    'portfolio.label': 'Nuestro trabajo',
    'portfolio.h2': 'Proyectos Recientes',
    'portfolio.sub': 'Productos reales, entregados y funcionando.',
    'proj.studysnap.title': 'StudySnap',
    'proj.studysnap.desc': 'Extensión de Chrome con IA que captura preguntas en pantalla y entrega respuestas instantáneas con explicaciones — impulsada por Claude Vision API.',
    'proj.clarity.title': 'Clarity Extension',
    'proj.clarity.desc': 'Extensión de navegador que detecta y resalta patrones oscuros en sitios web en tiempo real — protegiendo a los usuarios mientras navegan.',
    'proj.foto.title': 'FotoExpress Peru',
    'proj.foto.desc': 'Sitio web completo para empresa de fotografía en Perú — diseño moderno, showcase de servicios y flujo de contacto para clientes locales e internacionales.',
    'proj.yours.title': 'Podría ser el tuyo',
    'proj.yours.desc': 'Estamos tomando nuevos proyectos. Tu solución podría aparecer aquí. Construyamos algo que marque la diferencia.',
    'proj.yours.cta': 'Iniciar una conversación →',

    /* PRICING */
    'pricing.label': 'Inversión',
    'pricing.h2': 'Precios Transparentes',
    'pricing.sub': 'Cada proyecto se cotiza individualmente. Estos son puntos de partida — el trabajo complejo se cotiza después de una llamada gratuita.',
    'price.web.title': 'Diseño Web',
    'price.web.li1': 'Landing page',
    'price.web.li2': 'Responsive para móvil',
    'price.web.li3': 'Listo para SEO',
    'price.web.li4': 'Sitio completo desde $1,200',
    'price.web.btn': 'Solicitar cotización',
    'price.auto.title': 'Automatización',
    'price.auto.li1': 'Automatización app-a-app',
    'price.auto.li2': 'Flujos de disparador + acción',
    'price.auto.li3': 'Pruebas y documentación',
    'price.auto.li4': 'n8n complejo desde $1,200',
    'price.auto.btn': 'Solicitar cotización',
    'price.ai.title': 'Integración de IA',
    'price.ai.li1': 'Conexión a API de IA',
    'price.ai.li2': 'Prompting y lógica personalizada',
    'price.ai.li3': 'Pruebas y despliegue',
    'price.ai.li4': 'Sistemas completos desde $2,500',
    'price.ai.btn': 'Solicitar cotización',
    'price.chrome.title': 'Extensión de Chrome',
    'price.chrome.li1': 'Compatible con Manifest V3',
    'price.chrome.li2': 'Popup + scripts de contenido',
    'price.chrome.li3': 'Listo para integración de API',
    'price.chrome.li4': 'Con IA desde $1,500',
    'price.chrome.btn': 'Solicitar cotización',
    'price.social.title': 'Automatización Social',
    'price.social.li1': 'Pipelines de auto-publicación',
    'price.social.li2': 'Automatización de DMs',
    'price.social.li3': 'Programación entre plataformas',
    'price.social.li4': 'Dashboards analíticos desde $800',
    'price.social.btn': 'Solicitar cotización',
    'price.chatbot.title': 'Chatbot de IA',
    'price.chatbot.li1': 'WhatsApp / Instagram / Web',
    'price.chatbot.li2': 'Base de conocimiento personalizada',
    'price.chatbot.li3': 'Lógica de calificación de leads',
    'price.chatbot.li4': 'Multi-plataforma desde $1,500',
    'price.chatbot.btn': 'Solicitar cotización',

    /* FAQ (index) */
    'faq.label': 'Preguntas frecuentes',
    'faq.h2': 'Antes de contactarnos',
    'faq.sub': 'Las preguntas que todo cliente hace — respondidas por adelantado.',
    'faq.q1': '¿Cuánto tiempo toma un proyecto?',
    'faq.a1': 'Depende del alcance. Una landing page toma 3–5 días. Una extensión de Chrome 1–2 semanas. Una integración de IA 1–3 semanas. Te damos un cronograma claro antes de empezar.',
    'faq.q2': '¿Requieren un depósito?',
    'faq.a2': 'Sí — 50% al inicio, 50% al entregar. Esto protege a ambos lados y mantiene el proyecto avanzando. Aceptamos transferencia bancaria, PayPal y Stripe.',
    'faq.q3': '¿Qué pasa si no estoy satisfecho?',
    'faq.a3': 'Incluimos rondas de revisión en cada proyecto y trabajamos contigo hasta que esté bien. No cerramos un proyecto hasta que estés satisfecho.',
    'faq.q4': '¿Pueden trabajar con un presupuesto pequeño?',
    'faq.a4': 'Sí. Nuestros precios reflejan trabajo real y eficiente — sin overhead de agencia inflado. Si tu presupuesto es ajustado, dinos y adaptamos algo que funcione.',
    'faq.q5': '¿Soy dueño de todo después de la entrega?',
    'faq.a5': '100%. Todo el código, activos y cuentas se te entregan al final de cada proyecto. Sin ataduras, sin tarifas mensuales.',
    'faq.q6': '¿Trabajan con clientes fuera de EE.UU.?',
    'faq.a6': 'Absolutamente — la mayoría de nuestros clientes son internacionales. Trabajamos en diferentes zonas horarias, en inglés y español.',

    /* CONTACT (index) */
    'contact.label': 'Hablemos',
    'contact.h2': 'Inicia un proyecto<br>con nosotros',
    'contact.p': 'Cuéntanos qué estás construyendo o qué problema necesitas resolver. Respondemos en 24 horas con un camino claro — sin compromiso requerido.',
    'contact.loc': 'Utah, EE.UU.',
    'contact.world': 'Disponible en todo el mundo',
    'contact.time': 'Respuesta en 24 horas',
    'contact.call': 'Llamada de descubrimiento gratuita',
    'contact.name.label': 'Nombre',
    'contact.name.ph': 'Tu nombre',
    'contact.email.label': 'Correo electrónico',
    'contact.svc.label': 'Servicio',
    'contact.svc.ph': 'Selecciona un servicio',
    'contact.budget.label': 'Presupuesto estimado',
    'contact.budget.ph': 'Selecciona un rango',
    'contact.msg.label': 'Cuéntanos sobre tu proyecto',
    'contact.msg.ph': '¿Qué estás tratando de construir o automatizar?',
    'contact.btn': 'Enviar Mensaje →',
    'contact.success': '✓ ¡Mensaje enviado! Te contactaremos en 24 horas.',

    /* FOOTER */
    'footer.copy': '© 2025 FlowForge · Utah, EE.UU. · Entrega global.',

    /* ── SLC PAGE ── */
    'slc.trust1': 'Equipo en Utah',
    'slc.trust2': '10+ sitios entregados',
    'slc.trust3': 'Inglés y español',
    'slc.trust4': 'Respuesta en < 24h',
    'slc.trust5': 'Todo tuyo',

    'slc.niches.label': 'Con quién trabajamos',
    'slc.niches.h2': 'Hecho para los negocios<br>que mantienen Salt Lake City en marcha.',
    'slc.niches.sub': 'No somos para todos. Trabajamos con negocios de servicio serios en crecer — y que ya se cansaron de sitios web que no hacen nada.',
    'slc.n1.title': 'Contratistas de Servicios para el Hogar',
    'slc.n1.sub': 'Techos · HVAC · Plomería · Paisajismo · Electricistas',
    'slc.n1.p1': 'Tus clientes te buscan en Google antes de llamar. Si tu sitio es lento, feo o no aparece — están llamando a tu competencia.',
    'slc.n1.p2': 'Construimos sitios para contratistas que aparecen en Google, cargan rápido en cualquier teléfono y hacen súper fácil solicitar una cotización en menos de 30 segundos.',
    'slc.n1.result': '<span>Lo que obtienes:</span> Más solicitudes de cotización. Menos ausencias. Un sitio que trabaja mientras estás en el trabajo.',
    'slc.n1.cta': 'Obtén una auditoría gratis →',
    'slc.n2.title': 'Negocios de Fitness y Bienestar',
    'slc.n2.sub': 'Gimnasios · Entrenadores personales · Yoga · Terapeutas de masaje',
    'slc.n2.p1': 'Tus fotos de transformación están en Instagram. Tu link de reservas está enterrado en la bio. Tu sitio web parece del 2014.',
    'slc.n2.p2': 'Lo arreglamos. Construimos sitios de fitness con ofertas de prueba claras, horarios y flujos de reserva que convierten visitantes en miembros pagos — sin gastar más en anuncios.',
    'slc.n2.result': '<span>Lo que obtienes:</span> Más inscripciones de prueba. Más sesiones reservadas. Un sitio que vende tus servicios las 24 horas.',
    'slc.n2.cta': 'Obtén una auditoría gratis →',
    'slc.n3.title': 'Negocios Latinos en Utah',
    'slc.n3.sub': 'Restaurantes · Salones · Limpieza · Retail · Cualquier servicio local',
    'slc.n3.p1': 'Tu comunidad está aquí. Tus clientes hablan español e inglés. La mayoría de las agencias web no — y se nota.',
    'slc.n3.p2': 'Construimos sitios web bilingües (inglés + español) que representan tu negocio correctamente, conectan con tu comunidad y atraen clientes de ambas audiencias.',
    'slc.n3.result': '<span>Lo que obtienes:</span> Un sitio que habla tu idioma — literalmente. Más clientes, más confianza, más llamadas.',
    'slc.n3.cta': 'Hablemos →',

    'slc.del.label': 'Entregables',
    'slc.del.h2': 'Sin misterios. Exactamente lo que recibes.',
    'slc.del.sub': 'La mayoría de las agencias son vagas para poder cobrarte más después. Nosotros no.',
    'slc.web.block.title': '🌐 Tu Sitio Web',
    'slc.web.block.desc': 'Un sitio rápido, mobile-first construido para convertir visitantes en clientes — no solo para verse bonito.',
    'slc.web.li1': 'Diseño mobile-first — se ve bien en cualquier teléfono',
    'slc.web.li2': '5–8 páginas: Inicio, Servicios, Nosotros, Contacto + páginas específicas',
    'slc.web.li3': 'Tiempos de carga rápidos (menos de 3 segundos)',
    'slc.web.li4': 'Formularios y flujos de cotización optimizados para convertir',
    'slc.web.li5': 'Integración con Google Maps + páginas de ubicación para SEO local',
    'slc.web.li6': 'Galerías antes/después, reservas, páginas bilingües según el negocio',
    'slc.web.li7': 'Conectado a tu Google Business Profile',
    'slc.web.always.title': 'Incluido en cada proyecto',
    'slc.web.always.li1': 'Propiedad total — código, dominio, cuentas',
    'slc.web.always.li2': '30 días de soporte post-lanzamiento',
    'slc.web.always.li3': 'Puedes actualizarlo tú mismo (o nosotros lo manejamos)',
    'slc.auto.tag': 'Complemento Opcional',
    'slc.auto.block.title': '⚡ Automatizaciones',
    'slc.auto.block.desc': 'Deja que las máquinas manejen el seguimiento para que puedas enfocarte en el trabajo. Simple, confiable, conectado a tu teléfono.',
    'slc.auto.li1': 'Captura de lead → email o SMS instantáneo a tu prospecto',
    'slc.auto.li2': 'Notificaciones de nuevas consultas directo a tu teléfono',
    'slc.auto.li3': 'Resumen semanal: cuántos leads llegaron y de dónde',
    'slc.auto.li4': 'Integración con WhatsApp (especialmente valioso para negocios latinos)',
    'slc.auto.li5': 'Mensajes de confirmación y recordatorio de reserva',
    'slc.auto.li6': 'Solicitud de reseña en Google enviada automáticamente',
    'slc.auto.works.title': 'Funciona con',
    'slc.auto.works.li1': 'Tu email y teléfono existentes',
    'slc.auto.works.li2': 'WhatsApp, Gmail o cualquier bandeja que uses',
    'slc.auto.works.li3': 'Sin software nuevo que aprender',

    'slc.proc.label': 'El proceso',
    'slc.proc.h2': 'Proceso simple. Resultados reales.',
    'slc.step1.title': 'Auditoría Gratuita',
    'slc.step1.desc': 'Revisamos tu sitio actual, tus competidores y tus objetivos. Obtienes un panorama claro de qué está roto y cuánto costará arreglarlo. Sin compromiso, sin presión.',
    'slc.step2.title': 'Construimos',
    'slc.step2.desc': 'Apruebas el plan. Diseñamos, construimos y probamos tu sitio en 2–3 semanas. Recibes actualizaciones y puedes dar retroalimentación en cada paso.',
    'slc.step3.title': 'Consigues Clientes',
    'slc.step3.desc': 'Tu sitio sale en vivo. Los leads empiezan a llegar. Estamos contigo 30 días para asegurarnos de que todo funcione — luego entregamos la propiedad completa. El sitio es tuyo, para siempre.',
    'slc.proc.cta': 'Empezar con una auditoría gratis →',

    'slc.cases.label': 'Nuestro trabajo',
    'slc.cases.h2': 'Negocios reales. Resultados reales.',
    'slc.cases.sub': 'Proyectos entregados y funcionando — construidos aquí en Utah.',
    'slc.case1.type': 'Contratista · South Salt Lake',
    'slc.case1.title': 'Empresa de Techos — SLC',
    'slc.case1.result': '📈 Resultados próximamente',
    'slc.case2.type': 'Estudio de Fitness · Murray',
    'slc.case2.title': 'Gimnasio / Entrenador — SLC',
    'slc.case2.result': '📈 Resultados próximamente',
    'slc.case3.type': 'Negocio Latino · West Valley City',
    'slc.case3.title': 'Negocio Local — SLC',
    'slc.case3.result': '📈 Resultados próximamente',
    'slc.cases.next': '¿Quieres ser nuestro próximo caso de estudio?',
    'slc.cases.cta': 'Construyamos algo juntos →',

    'slc.pricing.label': 'Ofertas para tu negocio',
    'slc.pricing.h2': 'Un paquete por nicho.<br>Construido alrededor de tu problema real.',
    'slc.pricing.sub': 'No vendemos planes para todos. Esto es lo que recomendamos para cada tipo de negocio — y por qué.',
    'slc.fp1.name': 'Crecimiento para Contratistas',
    'slc.fp1.promise': '"Un sitio web que te hace aparecer en Google + seguimiento automatizado para que ningún lead se enfríe."',
    'slc.fp1.for.label': 'Ideal para',
    'slc.fp1.for.text': 'Contratistas que ya consiguen trabajos pero pierden leads porque nadie hace seguimiento rápido — o no saben cuántos leads están recibiendo.',
    'slc.fp1.li1': 'Sitio mobile-first — solicitud de cotización en menos de 60 segundos',
    'slc.fp1.li2': 'Nuevo lead → SMS a ti en 60 segundos',
    'slc.fp1.li3': 'Auto-respuesta al prospecto: "Te llamamos en menos de una hora"',
    'slc.fp1.li4': 'Seguimiento en 3 pasos si no hay respuesta (día 1, 3, 7)',
    'slc.fp1.li5': 'Solicitud de reseña en Google después de cada trabajo — automático',
    'slc.fp1.li6': 'Reporte semanal: leads recibidos, fuentes, estado del seguimiento',
    'slc.fp1.li7': '1 actualización del sitio/mes incluida',
    'slc.fp1.cta': 'Cotización para Contratistas',
    'slc.fp1.micro': 'Auditoría gratis incluida. Sin compromiso.',
    'slc.fp2.badge': '⭐ Primer paso recomendado',
    'slc.fp2.name': 'Lanzamiento Fitness',
    'slc.fp2.promise': '"Un sitio con flujo de reservas integrado que convierte visitantes en inscripciones de prueba."',
    'slc.fp2.for.label': 'Ideal para',
    'slc.fp2.for.text': 'Entrenadores y dueños de gimnasios que funcionan con Instagram y boca a boca — sin sitio web real o sin forma de reservar a alguien.',
    'slc.fp2.li1': 'Sitio de 6 páginas mobile-first',
    'slc.fp2.li2': 'CTA de oferta de prueba en cada página',
    'slc.fp2.li3': 'Formulario de reserva o integración con Calendly',
    'slc.fp2.li4': 'Sección de horario de clases integrada',
    'slc.fp2.li5': 'Galería de fotos de transformación',
    'slc.fp2.li6': 'Captura de email para oferta gratuita',
    'slc.fp2.li7': 'Sección de testimonios y prueba social',
    'slc.fp2.li8': 'Propiedad total — tuyo para siempre',
    'slc.fp2.cta': 'Cotización para Fitness',
    'slc.fp2.micro': 'Auditoría gratis incluida. Sin compromiso.',
    'slc.fp3.name': 'Lanzamiento Latino',
    'slc.fp3.promise': '"Un sitio bilingüe — inglés + español — que representa tu negocio correctamente y atrae clientes de ambas comunidades."',
    'slc.fp3.for.label': 'Ideal para',
    'slc.fp3.for.text': 'Negocios latinos sin sitio, con uno solo en inglés, o con uno que no representa la calidad de su negocio.',
    'slc.fp3.li1': 'Sitio completamente bilingüe — inglés + español',
    'slc.fp3.li2': 'Botón de idioma integrado (EN / ES)',
    'slc.fp3.li3': '5–7 páginas según el tipo de negocio',
    'slc.fp3.li4': 'Botón de WhatsApp (flotante + en pie de página)',
    'slc.fp3.li5': 'Galería de fotos: comida, servicios, equipo, espacio',
    'slc.fp3.li6': 'Configuración bilingüe de Google Business Profile',
    'slc.fp3.li7': 'SEO local básico en ambos idiomas',
    'slc.fp3.li8': 'Propiedad total — tuyo para siempre',
    'slc.fp3.cta': 'Hablemos / Get a quote',
    'slc.fp3.micro': 'Auditoría gratis · Free audit included.',
    'slc.upsell': 'Cada paquete de Lanzamiento puede crecer a un plan mensual de <strong>Crecimiento</strong> o <strong>Dominio</strong> una vez que tu sitio esté en vivo.',
    'slc.upsell.cta': 'Preguntar sobre opciones completas →',

    'slc.why.label': 'Por qué nosotros',
    'slc.why.h2': 'No somos una agencia.<br>Somos tu constructor local.',
    'slc.why1.title': 'Con base en Utah, enfocados en SLC',
    'slc.why1.desc': 'No somos una agencia remota que subcontrata tu proyecto. Estamos aquí. Conocemos Salt Lake City, el mercado, y nos importa tu negocio porque estamos construyendo el nuestro aquí también.',
    'slc.why2.title': 'Bilingüe por defecto',
    'slc.why2.desc': 'Inglés y español — no como truco, sino como capacidad real. Si tus clientes hablan español, tu sitio también debería. Lo escribimos, diseñamos y rankeamos para ambas audiencias.',
    'slc.why3.title': 'Anti-agencia, pro-resultados',
    'slc.why3.desc': 'Sin gerentes de cuenta. Sin tarifas de retención por cosas que no necesitas. Hablas directamente con la persona que construye tu sitio. Decimos lo que haremos y lo hacemos — a tiempo, siempre.',
    'slc.why4.title': 'Tú eres dueño de todo',
    'slc.why4.desc': 'Cuando entregamos tu sitio, es tuyo — código, dominio, cuentas, todo. Sin ataduras mensuales, sin tarifas ocultas. Nunca dependes de nosotros para mantener vivo tu sitio.',

    'slc.ap.badge': 'Nuevo · FlowForge AutoPilot',
    'slc.ap.h2': 'Tu marketing en piloto automático.<br>Menos de $6 al día.',
    'slc.ap.p': 'Una vez que tu sitio esté en vivo, agrega AutoPilot y tu marketing funciona solo — publicaciones sociales, seguimientos, actualizaciones de Google, solicitudes de reseñas y un reporte cada lunes. En inglés y español.',
    'slc.ap.li1': '5 publicaciones sociales/semana — Instagram + Facebook, bilingüe',
    'slc.ap.li2': 'Nuevo lead → SMS a ti en 60 segundos + auto-respuesta al prospecto',
    'slc.ap.li3': 'Google Business Profile actualizado semanalmente',
    'slc.ap.li4': 'Solicitudes de reseña enviadas automáticamente',
    'slc.ap.li5': 'Reporte semanal cada lunes por la mañana',
    'slc.ap.li6': 'Agente de chat en el sitio — captura leads 24/7',
    'slc.ap.vs': 'vs $249–399/mes para herramientas de IA genéricas sin español y sin conocimiento local',
    'slc.ap.cta': 'Preguntar sobre AutoPilot →',
    'slc.ap.note': 'Solo para clientes con sitio de FlowForge.',

    'slc.faq.label': 'Preguntas frecuentes',
    'slc.faq.h2': 'Antes de contactarnos.',
    'slc.faq.sub': 'Las preguntas que todo dueño de negocio en SLC hace — respondidas directamente.',
    'slc.faq.q1': '¿No puedo simplemente usar una herramienta de marketing con IA?',
    'slc.faq.a1': 'Puedes — y algunas son buenas programando publicaciones. Pero esto es lo que no pueden hacer: construirte un sitio que convierta visitantes en llamadas. Arreglar un Google Business Profile mal configurado. Escribir en español real. O contestar cuando algo se rompe.<br><br>Las herramientas de IA se apoyan en lo que ya tienes. Si lo que tienes está roto — solo automatizan el problema. Nosotros arreglamos la base primero.',
    'slc.faq.q2': '¿Cuánto tiempo toma un proyecto?',
    'slc.faq.a2': 'Un sitio Launch típicamente está listo en 2–3 semanas desde que apruebas el plan. Nos movemos rápido — un punto de contacto, sin comités. Verás progreso cada pocos días, no una vez al mes.',
    'slc.faq.q3': '¿Tengo que pagar todo por adelantado?',
    'slc.faq.a3': 'No. Es 50% para empezar, 50% cuando entregamos. Aceptamos transferencia bancaria, PayPal y Stripe. Los planes mensuales comienzan después de que el sitio esté en vivo.',
    'slc.faq.q4': '¿Y si ya tengo un sitio web?',
    'slc.faq.a4': 'Lo revisamos en la auditoría gratuita y te decimos honestamente: arreglamos lo que tienes o empezamos de cero. A veces unos cambios específicos son suficientes.',
    'slc.faq.q5': '¿Realmente escriben en español o solo traducen?',
    'slc.faq.a5': 'Lo escribimos. Hay una diferencia real entre español corporativo traducido y texto que suena natural para una comunidad hispanohablante en Utah. Somos bilingües — sabemos la diferencia.',
    'slc.faq.q6': '¿Qué soy dueño al final?',
    'slc.faq.a6': 'Todo. Código, dominio, cuenta de hosting, Google Business Profile — todo se te entrega al momento de la entrega. Sin ataduras, sin tarifa mensual. Es tuyo. Punto final.',

    'slc.final.label': 'Hablemos',
    'slc.final.h2': '¿Listo para un sitio web<br>que realmente funcione?',
    'slc.final.p': 'Empecemos con una auditoría gratuita de 20 minutos. Revisaremos tu sitio, te diremos exactamente qué te está frenando y te daremos un plan claro — sin compromisos.<br><br>La mayoría de los clientes se van con al menos 3 cosas que pueden mejorar de inmediato, trabajen con nosotros o no.',
    'slc.final.btn1': 'Reservar Mi Auditoría Gratuita',
    'slc.final.btn2': 'Mensaje en WhatsApp →',
    'slc.final.micro': 'Sin compromiso. Sin discurso de ventas. Solo una mirada directa a tu presencia en línea.',
    'slc.final.cities': '📍 Sirviendo Salt Lake City y alrededores<br>West Valley City · Murray · Sandy · Draper · South Salt Lake · Millcreek · Provo · Ogden',
  }
};

function setLang(lang) {
  localStorage.setItem('ff-lang', lang);
  document.documentElement.lang = lang;

  // SLC hero show/hide blocks (if present)
  const heroEn = document.getElementById('hero-en');
  const heroEs = document.getElementById('hero-es');
  if (heroEn) heroEn.classList.toggle('active', lang === 'en');
  if (heroEs) heroEs.classList.toggle('active', lang === 'es');

  // data-i18n → textContent
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const val = FF_LANG[lang]?.[el.dataset.i18n];
    if (val !== undefined) el.textContent = val;
  });

  // data-i18n-html → innerHTML
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const val = FF_LANG[lang]?.[el.dataset.i18nHtml];
    if (val !== undefined) el.innerHTML = val;
  });

  // data-i18n-ph → placeholder
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const val = FF_LANG[lang]?.[el.dataset.i18nPh];
    if (val !== undefined) el.placeholder = val;
  });

  // lang toggle buttons
  document.querySelectorAll('.lang-btn').forEach(b => {
    b.classList.toggle('active', b.dataset.lang === lang);
  });
}

// Init
document.addEventListener('DOMContentLoaded', function () {
  const lang = localStorage.getItem('ff-lang') || 'en';
  setLang(lang);
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => setLang(btn.dataset.lang));
  });
});
